name: humanoid
channels:
  - <unknown>
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.4=py39h06a4308_1
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpc=1.0.3=0
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - pytorch=2.3.0=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.7=py39_cu121_pyt210
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - sympy=1.13.2=py39h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.3.0=py39_cu121
  - torchtriton=2.3.0=py39
  - torchvision=0.18.0=py39_cu121
  - typing_extensions=4.11.0=py39h06a4308_0
  - urllib3=2.2.3=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - attrs==24.2.0
      - blinker==1.8.2
      - bokeh==3.4.3
      - brax==0.9.4
      - cffi==1.17.1
      - chex==0.1.87
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.28
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==4.4.2
      - dm-control==1.0.19
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - flask==3.0.3
      - flask-cors==5.0.0
      - flax==0.8.5
      - fonttools==4.54.1
      - freetype-py==2.5.1
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - grpcio==1.67.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - gymnax==0.0.6
      - humanize==4.11.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipdb==0.13.13
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jax==0.4.28
      - jax-cuda12-pjrt==0.4.28
      - jax-cuda12-plugin==0.4.28
      - jaxlib==0.4.28
      - jaxopt==0.8.3
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.5.0
      - moviepy==1.0.3
      - msgpack==1.1.0
      - mujoco==3.1.5
      - mujoco-mjx==3.1.5
      - mujoco-py==2.1.2.14
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==1.23.4
      - nvidia-cublas-cu12==12.6.3.3
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.77
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optax==0.2.3
      - orbax-checkpoint==0.6.4
      - packaging==24.1
      - pandas==2.2.3
      - parso==0.8.4
      - patchelf==0.17.2.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - proglog==0.1.10
      - prompt-toolkit==3.0.48
      - protobuf==5.28.3
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pyglet==2.0.18
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytinyrenderer==0.0.14
      - pytz==2024.2
      - rdkit==2024.9.4
      - referencing==0.35.1
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.21.0
      - scikit-learn==1.5.2
      - scipy==1.11.0
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - setuptools==61.2.0
      - smmap==5.0.1
      - smplx==0.1.28
      - soundfile==0.13.0
      - stable-baselines3==2.3.2
      - stack-data==0.6.3
      - submitit==1.5.2
      - tenacity==9.0.0
      - tensorboardx==2.6.2.2
      - tensordict==0.4.0
      - tensorstore==0.1.67
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tomli==2.0.2
      - toolz==1.0.0
      - torchrl==0.4.0
      - tornado==6.4.2
      - tqdm==4.67.0
      - traitlets==5.14.3
      - trimesh==4.5.2
      - tzdata==2024.2
      - wandb==0.18.6
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - xyzservices==2024.9.0
      - zipp==3.20.2

